# .air.toml

# Set working directory if needed
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main.exe Delivery/main.go"
bin = "tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
delay = 200
stop_on_error = true
log = "stdout"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true